#!/usr/bin/env bash

CURRENT_DIR="$(readlink -e "${BASH_SOURCE[0]%/*}")"

if [[ $1 == '--debug' ]]; then
  echo "$*" | gawk -f $CURRENT_DIR/tmux-printer.awk
else
  eval "echo -e \"$(echo "$*" | gawk -f $CURRENT_DIR/tmux-printer.awk)\""
fi
